using Windows.Globalization;

// App text in the 10 most spoken languages. The language comes from the operating system; if it is not
// in the list, English is used.
//
// ponytail: no .resw files and no per-language package, which is what publishing to the store would need.
// When that day comes: move these keys to .resw without touching the S.T() calls.
static class S
{
    // Language chosen by the person; if they never chose one, the operating system decides.
    // Resolved on first use, not in the initializer: the text table has to exist beforehand.
    static string? _lang;
    internal static string Lang
    {
        get => _lang ??= Pick(ApplicationLanguages.Languages.FirstOrDefault() ?? "en");
        set => _lang = Table.ContainsKey(value) ? value : "en";
    }

    static string Pick(string tag)
    {
        var i = tag.IndexOf('-');
        var two = (i < 0 ? tag : tag[..i]).ToLowerInvariant();
        return Table.ContainsKey(two) ? two : "en";
    }

    internal static string T(string key) =>
        Table[Lang].TryGetValue(key, out var v) ? v : Table["en"][key];

    internal static string F(string key, string arg) => T(key).Replace("{0}", arg);

    // Name of each language in its own language, the way a speaker would write it.
    internal static string Name(string code) => code switch
    {
        "es" => "Español",
        "fr" => "Français",
        "ru" => "Русский",
        "zh" => "中文",
        "ja" => "日本語",
        "pt" => "Português",
        "hi" => "हिन्दी",
        "ar" => "العربية",
        "bn" => "বাংলা",
        _ => "English",
    };

    internal static readonly string[] Codes = { "en", "es", "fr", "ru", "zh", "ja", "pt", "hi", "ar", "bn" };

    static readonly Dictionary<string, Dictionary<string, string>> Table = new()
    {
        ["en"] = new()
        {
            ["pickTitle"] = "Choose the profile to open this link:",
            ["settings"] = "Settings",
            ["dialogTitle"] = "Browsers to show",
            ["save"] = "Save",
            ["cancel"] = "Cancel",
            ["empty"] = "No browsers or profiles were found.",
            ["detectedBy"] = "Detected by: ",
            ["needOne"] = "Leave at least one browser selected.",
            ["singleProfile"] = "{0} (single profile)",
            ["whyProcess"] = "process",
            ["whyCmdline"] = "command line",
            ["whyWindow"] = "window",
            ["whyLock"] = "lock file",
            ["whyLastActive"] = "last active",
            ["crash"] = "BrowSel closed because of an unexpected error.",
            ["noDetail"] = "no details available",
            ["noArgs"] = "Run: BrowSel.exe --register (or --unregister to remove it)\nThen pick 'BrowSel' as your default browser.",
            ["dotnetHint"] = "Build with 'dotnet build' and run BrowSel.exe directly.",
            ["appDescription"] = "Pick the browser and profile for each link",
            ["registered"] = "BrowSel is registered, but it is NOT your default browser yet. Windows requires you to confirm it: in the Settings window that just opened, find BrowSel and set it for HTTP and HTTPS.",
            ["unregistered"] = "BrowSel was unregistered. If it was still the default, Windows will ask you to pick another browser when you open a link.",
            ["openInEditor"] = "Editor",
            ["copyLink"] = "Copy",
            ["editor"] = "Open links in",
            ["editorTip"] = "Only editors that Windows has associated with .txt files are listed. To add another one: right-click any .txt file, choose 'Open with', pick the editor and tick 'Always use this app'.",
            ["langLabel"] = "App language",
            ["checkUpdates"] = "Check for updates",
            ["checking"] = "Checking...",
            ["upToDate"] = "You already have the latest version.",
            ["updateFailed"] = "Could not check for updates. Check your internet connection.",
            ["confirmUpdate"] = "Do you want to install v{0}?",
            ["downloading"] = "Downloading...",
            ["yes"] = "Yes",
            ["no"] = "No"
        },
        ["es"] = new()
        {
            ["pickTitle"] = "Elige el perfil para abrir este enlace:",
            ["settings"] = "Ajustes",
            ["dialogTitle"] = "Navegadores a mostrar",
            ["save"] = "Guardar",
            ["cancel"] = "Cancelar",
            ["empty"] = "No se encontraron navegadores ni perfiles.",
            ["detectedBy"] = "Detectado por: ",
            ["needOne"] = "Deja al menos un navegador seleccionado.",
            ["singleProfile"] = "{0} (perfil único)",
            ["whyProcess"] = "proceso",
            ["whyCmdline"] = "línea de comandos",
            ["whyWindow"] = "ventana",
            ["whyLock"] = "archivo de bloqueo",
            ["whyLastActive"] = "último uso",
            ["crash"] = "BrowSel se cerró por un error inesperado.",
            ["noDetail"] = "sin detalle",
            ["noArgs"] = "Ejecuta: BrowSel.exe --register (o --unregister para quitarlo)\nLuego elige 'BrowSel' como navegador predeterminado.",
            ["dotnetHint"] = "Compila con 'dotnet build' y ejecuta BrowSel.exe directamente.",
            ["appDescription"] = "Selector de perfiles para enlaces",
            ["registered"] = "BrowSel quedó registrado, pero todavía NO es tu navegador predeterminado. Windows exige que lo confirmes: en la ventana de Configuración que se abrió, busca BrowSel y asígnalo a HTTP y HTTPS.",
            ["unregistered"] = "BrowSel fue desregistrado. Si seguía como predeterminado, Windows te pedirá elegir otro navegador al abrir un enlace.",
            ["openInEditor"] = "Editor",
            ["copyLink"] = "Copiar",
            ["editor"] = "Editor seleccionado",
            ["editorTip"] = "Solo se listan los editores que Windows asoció a archivos .txt. Para agregar otro: haz clic derecho en cualquier archivo .txt, elige 'Abrir con', selecciona el editor y marca 'Siempre usar esta aplicación'.",
            ["langLabel"] = "Idioma de la app",
            ["checkUpdates"] = "Buscar actualizaciones",
            ["checking"] = "Buscando...",
            ["upToDate"] = "Ya tienes la última versión.",
            ["updateFailed"] = "No se pudieron buscar actualizaciones. Revisa tu conexión a internet.",
            ["confirmUpdate"] = "¿Desea instalar la v{0}?",
            ["downloading"] = "Descargando...",
            ["yes"] = "Sí",
            ["no"] = "No"
        },
        ["fr"] = new()
        {
            ["pickTitle"] = "Choisissez le profil pour ouvrir ce lien :",
            ["settings"] = "Paramètres",
            ["dialogTitle"] = "Navigateurs à afficher",
            ["save"] = "Enregistrer",
            ["cancel"] = "Annuler",
            ["empty"] = "Aucun navigateur ni profil trouvé.",
            ["detectedBy"] = "Détecté par : ",
            ["needOne"] = "Laissez au moins un navigateur sélectionné.",
            ["singleProfile"] = "{0} (profil unique)",
            ["whyProcess"] = "processus",
            ["whyCmdline"] = "ligne de commande",
            ["whyWindow"] = "fenêtre",
            ["whyLock"] = "fichier verrou",
            ["whyLastActive"] = "dernier utilisé",
            ["crash"] = "BrowSel s'est fermé à cause d'une erreur inattendue.",
            ["noDetail"] = "aucun détail disponible",
            ["noArgs"] = "Exécutez : BrowSel.exe --register (ou --unregister pour le retirer)\nChoisissez ensuite « BrowSel » comme navigateur par défaut.",
            ["dotnetHint"] = "Compilez avec 'dotnet build' et exécutez BrowSel.exe directement.",
            ["appDescription"] = "Choisir le navigateur et le profil pour chaque lien",
            ["registered"] = "BrowSel est enregistré, mais ce n'est PAS encore votre navigateur par défaut. Windows exige une confirmation : dans la fenêtre Paramètres qui vient de s'ouvrir, recherchez BrowSel et définissez-le pour HTTP et HTTPS.",
            ["unregistered"] = "BrowSel a été désenregistré. S'il restait le navigateur par défaut, Windows vous demandera d'en choisir un autre à l'ouverture d'un lien.",
            ["openInEditor"] = "Éditeur",
            ["copyLink"] = "Copier",
            ["editor"] = "Ouvrir les liens dans",
            ["editorTip"] = "Seuls les éditeurs associés par Windows aux fichiers .txt sont listés. Pour en ajouter un : clic droit sur un fichier .txt, choisissez « Ouvrir avec », sélectionnez l'éditeur et cochez « Toujours utiliser cette application ».",
            ["langLabel"] = "Langue de l'application",
            ["checkUpdates"] = "Rechercher des mises à jour",
            ["checking"] = "Recherche...",
            ["upToDate"] = "Vous avez déjà la dernière version.",
            ["updateFailed"] = "Impossible de rechercher des mises à jour. Vérifiez votre connexion Internet.",
            ["confirmUpdate"] = "Voulez-vous installer la v{0} ?",
            ["downloading"] = "Téléchargement...",
            ["yes"] = "Oui",
            ["no"] = "Non"
        },
        ["ru"] = new()
        {
            ["pickTitle"] = "Выберите профиль для открытия этой ссылки:",
            ["settings"] = "Параметры",
            ["dialogTitle"] = "Показываемые браузеры",
            ["save"] = "Сохранить",
            ["cancel"] = "Отмена",
            ["empty"] = "Браузеры и профили не найдены.",
            ["detectedBy"] = "Обнаружено: ",
            ["needOne"] = "Оставьте выбранным хотя бы один браузер.",
            ["singleProfile"] = "{0} (один профиль)",
            ["whyProcess"] = "процесс",
            ["whyCmdline"] = "командная строка",
            ["whyWindow"] = "окно",
            ["whyLock"] = "файл блокировки",
            ["whyLastActive"] = "недавние",
            ["crash"] = "BrowSel закрылся из-за непредвиденной ошибки.",
            ["noDetail"] = "подробностей нет",
            ["noArgs"] = "Запустите: BrowSel.exe --register (или --unregister для удаления)\nЗатем выберите «BrowSel» браузером по умолчанию.",
            ["dotnetHint"] = "Соберите через 'dotnet build' и запустите BrowSel.exe напрямую.",
            ["appDescription"] = "Выбор браузера и профиля для каждой ссылки",
            ["registered"] = "BrowSel зарегистрирован, но пока НЕ является браузером по умолчанию. Windows требует подтверждения: в открывшемся окне параметров найдите BrowSel и назначьте его для HTTP и HTTPS.",
            ["unregistered"] = "BrowSel был удалён. Если он оставался браузером по умолчанию, Windows попросит выбрать другой браузер при открытии ссылки.",
            ["openInEditor"] = "Редактор",
            ["copyLink"] = "Копировать",
            ["editor"] = "Открывать ссылки в",
            ["editorTip"] = "Показываются только редакторы, которые Windows связал с файлами .txt. Чтобы добавить: щёлкните правой кнопкой по любому файлу .txt, выберите «Открыть с помощью», отметьте редактор и поставьте галочку «Всегда использовать это приложение».",
            ["langLabel"] = "Язык приложения",
            ["checkUpdates"] = "Проверить обновления",
            ["checking"] = "Проверка...",
            ["upToDate"] = "У вас уже последняя версия.",
            ["updateFailed"] = "Не удалось проверить обновления. Проверьте подключение к интернету.",
            ["confirmUpdate"] = "Установить версию {0}?",
            ["downloading"] = "Загрузка...",
            ["yes"] = "Да",
            ["no"] = "Нет"
        },
        ["zh"] = new()
        {
            ["pickTitle"] = "选择用于打开此链接的配置文件：",
            ["settings"] = "设置",
            ["dialogTitle"] = "要显示的浏览器",
            ["save"] = "保存",
            ["cancel"] = "取消",
            ["empty"] = "未找到浏览器或配置文件。",
            ["detectedBy"] = "检测方式：",
            ["needOne"] = "至少保留一个浏览器。",
            ["singleProfile"] = "{0}（单一配置文件）",
            ["whyProcess"] = "进程",
            ["whyCmdline"] = "命令行",
            ["whyWindow"] = "窗口",
            ["whyLock"] = "锁定文件",
            ["whyLastActive"] = "最近使用",
            ["crash"] = "BrowSel 因意外错误而关闭。",
            ["noDetail"] = "无详细信息",
            ["noArgs"] = "运行：BrowSel.exe --register（或 --unregister 卸载）\n然后将 BrowSel 设为默认浏览器。",
            ["dotnetHint"] = "使用 'dotnet build' 编译，然后直接运行 BrowSel.exe。",
            ["appDescription"] = "为每个链接选择浏览器和配置文件",
            ["registered"] = "BrowSel 已注册，但尚不是你的默认浏览器。Windows 要求手动确认：在刚打开的设置窗口中找到 BrowSel，并将其设置为 HTTP 和 HTTPS。",
            ["unregistered"] = "BrowSel 已注销。如果它仍是默认浏览器，Windows 会在打开链接时要求你选择其他浏览器。",
            ["openInEditor"] = "编辑器",
            ["copyLink"] = "复制",
            ["editor"] = "打开链接使用",
            ["editorTip"] = "只列出 Windows 已与 .txt 文件关联的编辑器。要添加其他编辑器：右键点击任意 .txt 文件，选择“打开方式”，选中编辑器并勾选“始终使用此应用”。",
            ["langLabel"] = "应用语言",
            ["checkUpdates"] = "检查更新",
            ["checking"] = "正在检查...",
            ["upToDate"] = "你已经是最新版本。",
            ["updateFailed"] = "无法检查更新。请检查你的网络连接。",
            ["confirmUpdate"] = "要安装 {0} 吗？",
            ["downloading"] = "正在下载...",
            ["yes"] = "是",
            ["no"] = "否"
        },
        ["ja"] = new()
        {
            ["pickTitle"] = "このリンクを開くプロファイルを選択してください：",
            ["settings"] = "設定",
            ["dialogTitle"] = "表示するブラウザー",
            ["save"] = "保存",
            ["cancel"] = "キャンセル",
            ["empty"] = "ブラウザーもプロファイルも見つかりませんでした。",
            ["detectedBy"] = "検出方法：",
            ["needOne"] = "少なくとも 1 つのブラウザーを選択してください。",
            ["singleProfile"] = "{0}（単一プロファイル）",
            ["whyProcess"] = "プロセス",
            ["whyCmdline"] = "コマンドライン",
            ["whyWindow"] = "ウィンドウ",
            ["whyLock"] = "ロックファイル",
            ["whyLastActive"] = "最後に使用",
            ["crash"] = "予期しないエラーが発生したため BrowSel を終了しました。",
            ["noDetail"] = "詳細情報はありません",
            ["noArgs"] = "実行：BrowSel.exe --register（削除は --unregister）\nその後、BrowSel を既定のブラウザーに設定してください。",
            ["dotnetHint"] = "'dotnet build' でビルドし、BrowSel.exe を直接実行してください。",
            ["appDescription"] = "リンクごとにブラウザーとプロファイルを選択",
            ["registered"] = "BrowSel は登録されましたが、まだ既定のブラウザーではありません。Windows では手動での確認が必要です。開いた設定ウィンドウで BrowSel を探し、HTTP と HTTPS に割り当ててください。",
            ["unregistered"] = "BrowSel の登録が解除されました。既定のブラウザーのままだった場合、リンクを開くときに別のブラウザーを選ぶよう求められます。",
            ["openInEditor"] = "エディター",
            ["copyLink"] = "コピー",
            ["editor"] = "リンクを開くアプリ",
            ["editorTip"] = "Windows が .txt ファイルに関連付けたエディターだけが表示されます。追加するには：任意の .txt ファイルを右クリック →「プログラムから開く」→ エディターを選択 →「常にこのアプリを使う」にチェックを入れます。",
            ["langLabel"] = "アプリの言語",
            ["checkUpdates"] = "更新を確認",
            ["checking"] = "確認中...",
            ["upToDate"] = "すでに最新バージョンです。",
            ["updateFailed"] = "更新を確認できませんでした。インターネット接続を確認してください。",
            ["confirmUpdate"] = "バージョン {0} をインストールしますか？",
            ["downloading"] = "ダウンロード中...",
            ["yes"] = "はい",
            ["no"] = "いいえ"
        },
        ["pt"] = new()
        {
            ["pickTitle"] = "Escolha o perfil para abrir este link:",
            ["settings"] = "Configurações",
            ["dialogTitle"] = "Navegadores a mostrar",
            ["save"] = "Salvar",
            ["cancel"] = "Cancelar",
            ["empty"] = "Nenhum navegador ou perfil encontrado.",
            ["detectedBy"] = "Detectado por: ",
            ["needOne"] = "Deixe pelo menos um navegador selecionado.",
            ["singleProfile"] = "{0} (perfil único)",
            ["whyProcess"] = "processo",
            ["whyCmdline"] = "linha de comando",
            ["whyWindow"] = "janela",
            ["whyLock"] = "arquivo de bloqueio",
            ["whyLastActive"] = "último uso",
            ["crash"] = "O BrowSel foi fechado devido a um erro inesperado.",
            ["noDetail"] = "sem detalhes",
            ["noArgs"] = "Execute: BrowSel.exe --register (ou --unregister para remover)\nDepois escolha 'BrowSel' como navegador padrão.",
            ["dotnetHint"] = "Compile com 'dotnet build' e execute o BrowSel.exe diretamente.",
            ["appDescription"] = "Escolha o navegador e o perfil para cada link",
            ["registered"] = "O BrowSel está registrado, mas ainda NÃO é o navegador padrão. O Windows exige confirmação: na janela Configurações que abriu, procure o BrowSel e defina-o para HTTP e HTTPS.",
            ["unregistered"] = "O BrowSel foi removido. Se ainda era o padrão, o Windows vai pedir que você escolha outro navegador ao abrir um link.",
            ["openInEditor"] = "Editor",
            ["copyLink"] = "Copiar",
            ["editor"] = "Abrir links em",
            ["editorTip"] = "Só são listados os editores que o Windows associou a arquivos .txt. Para adicionar outro: clique com o botão direito em um arquivo .txt, escolha 'Abrir com', selecione o editor e marque 'Sempre usar este aplicativo'.",
            ["langLabel"] = "Idioma do aplicativo",
            ["checkUpdates"] = "Verificar atualizações",
            ["checking"] = "Verificando...",
            ["upToDate"] = "Você já tem a versão mais recente.",
            ["updateFailed"] = "Não foi possível verificar atualizações. Confira sua conexão com a internet.",
            ["confirmUpdate"] = "Deseja instalar a v{0}?",
            ["downloading"] = "Baixando...",
            ["yes"] = "Sim",
            ["no"] = "Não"
        },
        ["hi"] = new()
        {
            ["pickTitle"] = "इस लिंक को खोलने के लिए प्रोफ़ाइल चुनें:",
            ["settings"] = "सेटिंग्स",
            ["dialogTitle"] = "दिखाने वाले ब्राउज़र",
            ["save"] = "सहेजें",
            ["cancel"] = "रद्द करें",
            ["empty"] = "कोई ब्राउज़र या प्रोफ़ाइल नहीं मिली।",
            ["detectedBy"] = "पहचान का तरीका: ",
            ["needOne"] = "कम से कम एक ब्राउज़र चुनें।",
            ["singleProfile"] = "{0} (एकल प्रोफ़ाइल)",
            ["whyProcess"] = "प्रक्रिया",
            ["whyCmdline"] = "कमांड लाइन",
            ["whyWindow"] = "विंडो",
            ["whyLock"] = "लॉक फ़ाइल",
            ["whyLastActive"] = "अंतिम उपयोग",
            ["crash"] = "अप्रत्याशित त्रुटि के कारण BrowSel बंद हो गया।",
            ["noDetail"] = "कोई विवरण नहीं",
            ["noArgs"] = "चलाएँ: BrowSel.exe --register (या हटाने के लिए --unregister)\nफिर 'BrowSel' को अपना डिफ़ॉल्ट ब्राउज़र चुनें।",
            ["dotnetHint"] = "'dotnet build' से बनाएँ और BrowSel.exe को सीधे चलाएँ।",
            ["appDescription"] = "हर लिंक के लिए ब्राउज़र और प्रोफ़ाइल चुनें",
            ["registered"] = "BrowSel पंजीकृत हो गया है, लेकिन अभी आपका डिफ़ॉल्ट ब्राउज़र नहीं है। Windows को इसे हाथ से पुष्टि करना होगा: जो सेटिंग विंडो खुली है उसमें BrowSel खोजें और उसे HTTP और HTTPS के लिए सेट करें।",
            ["unregistered"] = "BrowSel अपटोड हो गया। अगर यह डिफ़ॉल्ट बना था, तो Windows लिंक खोलते समय दूसरा ब्राउज़र चुनने को कहेगा।",
            ["openInEditor"] = "एडिटर",
            ["copyLink"] = "कॉपी करें",
            ["editor"] = "लिंक खोलने के लिए",
            ["editorTip"] = "केवल वही एडिटर दिखते हैं जिन्हें Windows ने .txt फ़ाइलों से जोड़ा है। कोई और जोड़ने के लिए: किसी भी .txt फ़ाइल पर राइट-क्लिक करें, 'ओपन विथ' चुनें, एडिटर चुनें और 'हमेशा इस ऐप का उपयोग करें' पर टिक करें।",
            ["langLabel"] = "ऐप की भाषा",
            ["checkUpdates"] = "अपडेट देखें",
            ["checking"] = "जाँच हो रही है...",
            ["upToDate"] = "आपके पास पहले से नवीनतम संस्करण है।",
            ["updateFailed"] = "अपडेट नहीं ढूंढे जा सके। अपना इंटरनेट कनेक्शन जाँचें।",
            ["confirmUpdate"] = "क्या आप v{0} इंस्टॉल करना चाहते हैं?",
            ["downloading"] = "डाउनलोड हो रहा है...",
            ["yes"] = "हाँ",
            ["no"] = "नहीं"
        },
        ["ar"] = new()
        {
            ["pickTitle"] = "اختر الملف الشخصي لفتح هذا الرابط:",
            ["settings"] = "الإعدادات",
            ["dialogTitle"] = "المتصفحات المعروضة",
            ["save"] = "حفظ",
            ["cancel"] = "إلغاء",
            ["empty"] = "لم يُعثر على متصفحات أو ملفات شخصية.",
            ["detectedBy"] = "تم اكتشافه بواسطة: ",
            ["needOne"] = "اترك متصفحًا واحدًا على الأقل محددًا.",
            ["singleProfile"] = "{0} (ملف شخصي واحد)",
            ["whyProcess"] = "عملية",
            ["whyCmdline"] = "سطر الأوامر",
            ["whyWindow"] = "نافذة",
            ["whyLock"] = "ملف القفل",
            ["whyLastActive"] = "آخر استخدام",
            ["crash"] = "أُغلق BrowSel بسبب خطأ غير متوقع.",
            ["noDetail"] = "لا تتوفر تفاصيل",
            ["noArgs"] = "شغّل: BrowSel.exe --register (أو --unregister للإزالة)\nثم اختر 'BrowSel' كمتصفح افتراضي.",
            ["dotnetHint"] = "ابنِ باستخدام 'dotnet build' ثم شغّل BrowSel.exe مباشرة.",
            ["appDescription"] = "اختر المتصفح والملف الشخصي لكل رابط",
            ["registered"] = "تم تسجيل BrowSel، لكنه ليس متصفحك الافتراضي بعد. يطلب Windows تأكيدًا يدويًا: في نافذة الإعدادات التي فُتحت، ابحث عن BrowSel وعيّنه لـ HTTP و HTTPS.",
            ["unregistered"] = "تمت إزالة تسجيل BrowSel. إذا كان لا يزال الافتراضي، فسيطلب منك Windows اختيار متصفح آخر عند فتح رابط.",
            ["openInEditor"] = "محرر النصوص",
            ["copyLink"] = "نسخ",
            ["editor"] = "فتح الروابط في",
            ["editorTip"] = "يعرض فقط المحرّرات التي ربطها Windows بملفات .txt. لإضافة محرّر آخر: انقر بالزر الأيمن على أي ملف ‎.txt، اختر 'فتح باستخدام'، اختر المحرّر، وحدّد 'دائمًا استخدم هذا التطبيق'.",
            ["langLabel"] = "لغة التطبيق",
            ["checkUpdates"] = "التحقق من التحديثات",
            ["checking"] = "جارٍ التحقق...",
            ["upToDate"] = "لديك أحدث إصدار بالفعل.",
            ["updateFailed"] = "تعذّر التحقق من التحديثات. تحقّق من اتصالك بالإنترنت.",
            ["confirmUpdate"] = "هل تريد تثبيت الإصدار {0}؟",
            ["downloading"] = "جارٍ التنزيل...",
            ["yes"] = "نعم",
            ["no"] = "لا"
        },
        ["bn"] = new()
        {
            ["pickTitle"] = "এই লিঙ্ক খোলার জন্য প্রোফাইল বেছে নিন:",
            ["settings"] = "সেটিংস",
            ["dialogTitle"] = "দেখানোর ব্রাউজার",
            ["save"] = "সংরক্ষণ",
            ["cancel"] = "বাতিল",
            ["empty"] = "কোনো ব্রাউজার বা প্রোফাইল পাওয়া যায়নি।",
            ["detectedBy"] = "শনাক্তকারী: ",
            ["needOne"] = "অন্তত একটি ব্রাউজার নির্বাচিত রাখুন।",
            ["singleProfile"] = "{0} (একক প্রোফাইল)",
            ["whyProcess"] = "প্রক্রিয়া",
            ["whyCmdline"] = "কমান্ড লাইন",
            ["whyWindow"] = "উইন্ডো",
            ["whyLock"] = "লক ফাইল",
            ["whyLastActive"] = "সর্বশেষ ব্যবহৃত",
            ["crash"] = "অপ্রত্যাশিত ত্রুটির কারণে BrowSel বন্ধ হয়েছে।",
            ["noDetail"] = "কোনো বিবরণ নেই",
            ["noArgs"] = "চালান: BrowSel.exe --register (বা সরাতে --unregister)\nতারপর ডিফল্ট ব্রাউজার হিসেবে 'BrowSel' নির্বাচন করুন।",
            ["dotnetHint"] = "'dotnet build' দিয়ে বিল্ড করুন এবং সরাসরি BrowSel.exe চালান।",
            ["appDescription"] = "প্রতিটি লিঙ্কের জন্য ব্রাউজার ও প্রোফাইল বেছে নিন",
            ["registered"] = "BrowSel নিবন্ধিত হয়েছে, তবে এটি এখনও আপনার ডিফল্ট ব্রাউজার নয়। Windows-এর হাতে নিশ্চিত করতে হবে: যে সেটিংস উইন্ডো খোলা হয়েছে তাতে BrowSel খুঁজে HTTP ও HTTPS-এর জন্য সেট করুন।",
            ["unregistered"] = "BrowSel অপটোজালকার হয়েছে। এটি যদি এখনও ডিফল্ট থাকে, তাহলে Windows লিঙ্ক খুললে অন্য ব্রাউজার বেছে নিতে বলবে।",
            ["openInEditor"] = "এডিটর",
            ["copyLink"] = "অনুলিপি",
            ["editor"] = "লিঙ্ক খোলার অ্যাপ",
            ["editorTip"] = "শুধু Windows যেসব সম্পাদককে .txt ফাইলের সঙ্গে যুক্ত করেছে সেগুলোই দেখানো হয়। আরেকটি যোগ করতে: যেকোনো .txt ফাইলে ডান ক্লিক করুন, 'ওপেন উইথ' বেছে নিন, সম্পাদক নির্বাচন করুন এবং 'সবসময় এই অ্যাপ ব্যবহার করুন' চেক করুন।",
            ["langLabel"] = "অ্যাপের ভাষা",
            ["checkUpdates"] = "আপডেট পরীক্ষা করুন",
            ["checking"] = "পরীক্ষা হচ্ছে...",
            ["upToDate"] = "আপনার কাছেই সর্বশেষ সংস্করণ আছে।",
            ["updateFailed"] = "আপডেট পরীক্ষা করা যায়নি। আপনার ইন্টারনেট সংযোগ দেখুন।",
            ["confirmUpdate"] = "আপনি কি v{0} ইনস্টল করতে চান?",
            ["downloading"] = "ডাউনলোড হচ্ছে...",
            ["yes"] = "হ্যাঁ",
            ["no"] = "না"
        },
    };
}
